management:
  endpoint:
      health:
        show-details: always
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "health,info"
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/comissarie
    username: postgres
    password: postgrespw
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          lob:
            non_contextual_creation: true

resilience4j:
  # https://blog.knoldus.com/bulkhead-with-resilience4j/
  bulkhead:
    metrics:
      enabled: true
    instances:
      countryCatalogService:
        maxConcurrentCalls: 5
        maxWaitDuration: 2000ms
        writable-stack-trace-enabled: false
  thread-pool-bulkhead:
    instances:
        countryCatalogService:
            coreThreadPoolSize: 5
            maxThreadPoolSize: 10
            queueCapacity: 10
            writable-stack-trace-enabled: false
            keep-alive-duration:
              60s
  # https://docs.spring.io/spring-cloud-circuitbreaker/docs/current/reference/html/
  # https://jsession4d.com/a-quick-guide-to-resilience4j-with-spring-boot/
  circuitbreaker:
    instances:
      countryCatalogService:
        registerHealthIndicator: true
        slidingWindowSize: 60
        slidingWindowType: TIME_BASED
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 10
        waitDurationInOpenState: 5s
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 2000
        failureRateThreshold: 50
